name: NeoDash CI/CD
 
on:
 push:
   branches: [ develop ]
 pull_request:
   branches: [ develop ]
 
jobs:
  build-npm:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [17.x]
   steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
       node-version: ${{ matrix.node-version }}
   - run: npm install
   - run: npm run-script build
   - run: npm pack
   - run: rm -rf target
   - run: mkdir target
   - run: mv *.tgz target/
   - run: tar -xvf target/*.tgz
   - run: rm -f target/*.tgz
   - run: cp package/dist/favicon.ico package/favicon.ico
   - run: echo "${{ secrets.NEO4J_LABS_APP_KEY }}" > neo4j-labs-app.pem 
   - run: echo "${{ secrets.NEO4J_LABS_APP_CERTIFICATE }}" > neo4j-labs-app.cert
   - run: npx @neo4j/code-signer --app ./package --private-key neo4j-labs-app.pem --cert neo4j-labs-app.cert --passphrase ${{ secrets.NEO4J_DESKTOP_PASSPHRASE }}
   - run: echo "${{ secrets.NEO4J_DESKTOP_CERTIFICATE }}" > neo4j_desktop.cert
   - run: npx @neo4j/code-signer --verify  --app ./package --root-cert neo4j_desktop.cert
   - run: cd package && npm pack
   - run: mv package/*.tgz ../
   - run: rm -rf package
   - run: tar xvf *.tgz package
   - run: npx @neo4j/code-signer --verify  --app ./package --root-cert neo4j_desktop.cert
   - run: rm -rf package
   - run: echo Done!
   - run: ls
   